name = "modrinth-resources-download"
author = "Dark2932"
version = "x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd111c6fa41e85305cfa4eb428e3dce67d392d50a1f2fd3d457c60c04c351d2d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
