name = "modrinth-resources-download"
author = "Dark2932"
version = "x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c93719d4086c047d58c29bff659343b934202851430724ef3d1e41b4837f755e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
